# Generated by Django 5.2.11 on 2026-02-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pop', models.IntegerField()),
                ('age', models.IntegerField()),
                ('description', models.TextField(default='Pas de description')),
            ],
        ),
        migrations.CreateModel(
            name='Loisir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_theatre', models.IntegerField()),
                ('nb_gymnase', models.IntegerField()),
                ('nb_musee', models.IntegerField()),
                ('ville', models.ForeignKey(db_column='villeId', on_delete=django.db.models.deletion.CASCADE, related_name='loisirs', to='api.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_mer', models.IntegerField()),
                ('dist_montagne', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('ville', models.OneToOneField(db_column='villeId', on_delete=django.db.models.deletion.CASCADE, related_name='localisation', to='api.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Lieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_bars', models.IntegerField()),
                ('nb_restaurants', models.IntegerField()),
                ('nb_soins', models.IntegerField()),
                ('nb_parcs', models.IntegerField()),
                ('ville', models.OneToOneField(db_column='villeId', on_delete=django.db.models.deletion.CASCADE, related_name='lieux', to='api.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Climat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('sun_hours', models.IntegerField()),
                ('ville', models.OneToOneField(db_column='villeId', on_delete=django.db.models.deletion.CASCADE, related_name='climat', to='api.ville')),
            ],
        ),
    ]
