# Generated by Django 6.0.2 on 2026-02-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_users_name_alter_users_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
